services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kirimailadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kirimailpassword}
      POSTGRES_DB: ${POSTGRES_DB:-kirimail}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kirimailadmin} -d ${POSTGRES_DB:-kirimail}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  meilisearch:
    image: getmeili/meilisearch:v1.42.1
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-kirimail-dev-master-key-for-local-only}
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  meili_data:
